Adds support for IH when using (i)loc_min(max)
static-frame/static-frame pull request #977
Opened 2024-09-23 18:45 UTC by chaburkland

@flexatone What are your thoughts on this solution to #937 ?

It's marked as a draft now because I didn't want to spend time implementing all the necessary unit tests if you reject the approach outright

If you like it, then I'll get it properly PR ready

2024-09-23 18:45 UTC, chaburkland commented
Refs #937

2024-09-24 15:50 UTC, flexatone commented
Thanks, @chaburkland , for this PR: this needed to be addressed! 

I see that you are returning a `Frame` when calling `loc_max` on a  `Frame` with `IndexHierarchy`, but returning a `Series` when calling `loc_max` on a `Frame` with a 1D index. Is this too surprising? We could always return a `Series`; in the case of an `IndexHierarchy`, the Series could be one of tuples for the IH labels, which makes using those values for selection in the same IH straight forward. 

One advantage of what you have done is that the IH name become the column labels: was that your motivation to going to a Frame?

2024-09-24 20:24 UTC, chaburkland commented
@flexatone I think you're right that getting back a Frame is a bit surprising. Let me fix it :upside_down_face:

2024-09-27 20:46 UTC, flexatone requested changes
Thanks for this PR! Just one opportunity here to use an `arraykit` function.

2024-09-27 20:46 UTC, flexatone commented on static_frame/core/frame.py
> +            post.flags.writeable = False
I think you can use `arraykit.array_to_tuple_array` for an optimized version of this move.

2024-10-01 20:19 UTC, flexatone approved these changes
Thanks!

2024-10-01 20:19 UTC, merged